// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsYOQesEAJfPFu4OzZ6jTCOqDfBIOQBa8',
    appId: '1:306558219646:web:1112e9026e04ce88bf2f2f',
    messagingSenderId: '306558219646',
    projectId: 'fruits-hub-5a2ff',
    authDomain: 'fruits-hub-5a2ff.firebaseapp.com',
    storageBucket: 'fruits-hub-5a2ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3j1MDJWJzthmwJScZ8_w3RMasgCEkbz4',
    appId: '1:306558219646:android:b8363a579d1c1b9bbf2f2f',
    messagingSenderId: '306558219646',
    projectId: 'fruits-hub-5a2ff',
    storageBucket: 'fruits-hub-5a2ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA18xFVvPz1HYrEvHB66dHBQOkYsdpXb5A',
    appId: '1:306558219646:ios:fe35be0a9856ed0dbf2f2f',
    messagingSenderId: '306558219646',
    projectId: 'fruits-hub-5a2ff',
    storageBucket: 'fruits-hub-5a2ff.firebasestorage.app',
    androidClientId: '306558219646-kp47u2nqnq7s6udgtopskjonvl5h617b.apps.googleusercontent.com',
    iosClientId: '306558219646-rqlukt8dntko831srni9m56723dqq1ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA18xFVvPz1HYrEvHB66dHBQOkYsdpXb5A',
    appId: '1:306558219646:ios:fe35be0a9856ed0dbf2f2f',
    messagingSenderId: '306558219646',
    projectId: 'fruits-hub-5a2ff',
    storageBucket: 'fruits-hub-5a2ff.firebasestorage.app',
    androidClientId: '306558219646-kp47u2nqnq7s6udgtopskjonvl5h617b.apps.googleusercontent.com',
    iosClientId: '306558219646-rqlukt8dntko831srni9m56723dqq1ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsYOQesEAJfPFu4OzZ6jTCOqDfBIOQBa8',
    appId: '1:306558219646:web:a0b1e9426fed9ae4bf2f2f',
    messagingSenderId: '306558219646',
    projectId: 'fruits-hub-5a2ff',
    authDomain: 'fruits-hub-5a2ff.firebaseapp.com',
    storageBucket: 'fruits-hub-5a2ff.firebasestorage.app',
  );
}
